"""Self-host the site's fonts as small subsets (run again whenever copy changes).

Downloads the open-source variable fonts from the google/fonts repository once (cached in
scripts/.font-src/), collects every character used in index.html and src/, and writes WOFF2
subsets to public/fonts/ plus src/styles/fonts.css.

    python scripts/fonts.py
"""
import pathlib, re, urllib.request, sys
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE = ROOT / 'scripts' / '.font-src'
OUT = ROOT / 'public' / 'fonts'
CSS = ROOT / 'src' / 'styles' / 'fonts.css'
GF = 'https://raw.githubusercontent.com/google/fonts/main/ofl/'

FONTS = [
    # family, file in google/fonts, output name, weight range, style, script
    ('Inter', 'inter/Inter%5Bopsz,wght%5D.ttf', 'inter', '100 900', 'normal', 'latin'),
    ('Instrument Serif', 'instrumentserif/InstrumentSerif-Regular.ttf', 'instrument-serif', '400', 'normal', 'latin'),
    ('Instrument Serif', 'instrumentserif/InstrumentSerif-Italic.ttf', 'instrument-serif-italic', '400', 'italic', 'latin'),
    ('JetBrains Mono', 'jetbrainsmono/JetBrainsMono%5Bwght%5D.ttf', 'jetbrains-mono', '100 800', 'normal', 'latin'),
    ('Noto Sans SC', 'notosanssc/NotoSansSC%5Bwght%5D.ttf', 'noto-sans-sc', '100 900', 'normal', 'cjk'),
    ('Noto Serif SC', 'notoserifsc/NotoSerifSC%5Bwght%5D.ttf', 'noto-serif-sc', '200 900', 'normal', 'cjk'),
]

def used_text():
    files = [ROOT / 'index.html'] + list((ROOT / 'src').rglob('*.js'))
    text = ''.join(p.read_text(encoding='utf-8') for p in files)
    text = re.sub(r'\\u([0-9a-fA-F]{4})', lambda m: chr(int(m.group(1), 16)), text)
    return text

def fetch(rel):
    CACHE.mkdir(parents=True, exist_ok=True)
    dst = CACHE / rel.split('/')[-1].replace('%5B', '[').replace('%5D', ']').replace(',', '_')
    if not dst.exists():
        print('downloading', rel)
        urllib.request.urlretrieve(GF + rel, dst)
    return dst

def main():
    text = used_text()
    ascii_set = ''.join(chr(c) for c in range(0x20, 0x7F))
    extra = '“”‘’—–…·×→←↗↩✓★☆—€£¥©®™°±²³⁴πσΣ⧉⌕▶'
    cjk = sorted({ch for ch in text if ord(ch) > 0x2E7F})
    latin = ascii_set + extra + ''.join(ch for ch in set(text) if 0x7F < ord(ch) <= 0x2E7F)
    OUT.mkdir(parents=True, exist_ok=True)
    css = ['/* generated by scripts/fonts.py — do not edit */']
    for family, rel, name, weight, style, script in FONTS:
        src = fetch(rel)
        chars = latin + ''.join(cjk) if script == 'cjk' else latin
        opts = subset.Options()
        opts.flavor = 'woff2'
        opts.layout_features = ['*']
        opts.name_IDs = ['*']
        opts.notdef_outline = True
        opts.drop_tables += ['DSIG']
        font = TTFont(src)
        sub = subset.Subsetter(options=opts)
        sub.populate(text=chars)
        sub.subset(font)
        out = OUT / f'{name}.woff2'
        font.flavor = 'woff2'
        font.save(out)
        print(f'{name}.woff2  {out.stat().st_size / 1024:.0f} KiB')
        css.append(f"@font-face {{ font-family: '{family}'; src: url('/fonts/{name}.woff2') format('woff2'); font-weight: {weight}; font-style: {style}; font-display: swap; }}")
    CSS.write_text('\n'.join(css) + '\n', encoding='utf-8')
    print(f'{len(cjk)} CJK characters')

if __name__ == '__main__':
    sys.exit(main())
